; Settings for running scripts on LCRC

[training.paths]
; Where to save the generated files
savedir_input = 
savedir_target = 
save_base_name_input = 
save_base_name_target = 
savedir_model = 
save_base_name_model = 

[training.mlp]
; MLP training specific settings
hidden_layers = 8, 8, 16, 16, 8
n_batches = 1
batch_size = 1_000
n_epochs = 100_000
step_size = 1e-3
loss_function = mse
seed = 0

[training.data]
; Training data specific settings
n_cosmo = 1_000
cosmo_sampling_method = LatinHypercube
logmhalo_min = 11.0
logmhalo_max = 15.0
n_halo = 500
seed = 
; For redshift, either provide specific array of values
; or min, max, and number for a linspace array
z_array = 0.0, 1.5, 2.5, 3.5, 5.0
z_min = 0
z_max = 5
n_z = 10
; files to generate
get_loss_data = True
get_hmf_best_fit = True

[cosmo.params.defaults]
; Default cosmology set to Planck 2018
; -- note that this section cannont contain anything else
;    other than the values of the cosmological parameters
flat = True
Om0 = 0.3111
sigma8 = 0.8102
ns = 0.9665
Ob0 = 0.0490
H0 = 67.66

[cosmo.params.priors]
; Parameter priors (param_min, param_max)
; -- note that this section cannont contain anything else
;    other than the the cosmological parameter priors
Om0 = 0.2, 0.5
sigma8 = 0.6, 1.0
ns = 0.8, 1.1

[hmf.model]
mdef = 200m
model = tinker08
q_out = dndlog10M
h_units = False

[hmf.fitter]
num_steps = 1000
step_size = 0.03
n_warmup = 1
hmf_cut = 1e-8
cuml = False